[build]
  base = "web"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Disable secret scanning (Firebase keys are public)
  SECRETS_SCAN_ENABLED = "false"
